// packages/create-umi/templates/vue-app/src/layouts/index.vue
<template>
  <div class="navs">
    <ul>
      <li>
        <router-link to="/">Home</router-link>
      </li>
      <li>
        <router-link to="/docs">Docs</router-link>
      </li>
      <li>
        <a href="https://github.com/umijs/umi">Github</a>
      </li>
    </ul>
    <router-view></router-view>
  </div>
</template>
<style lang="less">
  .navs {
    ul {
      padding: 0;
      list-style: none;
      display: flex;
    }
    li {
      margin-right: 1em;
    }
  }
</style>

// packages/create-umi/templates/app/layouts/index.tsx
import React from 'react';
// @ts-ignore
import { Link, Outlet } from 'umi';
import styles from './index.less';

export default function Layout() {
  return (
    <div className={styles.navs}>
      <ul>
        <li>
          <Link to="/">Home</Link>
        </li>
        <li>
          <Link to="/docs">Docs</Link>
        </li>
        <li>
          <a href="https://github.com/umijs/umi">Github</a>
        </li>
      </ul>
      <Outlet />
    </div>
  );
}
